export const metadata = {
  title: 'Create Next App',
  robots: { index: false, follow: false },
  description: 'Generated by create next app',
};

export default function DevLayout({ children }: { children: React.ReactNode }) {
  return <div className='h-500'>{children}</div>;
}
